# Generated by Django 4.1.4 on 2022-12-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='weigth',
            new_name='weight',
        ),
    ]
