# Generated by Django 4.1.4 on 2022-12-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_weigth_pet_weight'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='pets',
            field=models.ManyToManyField(related_name='traits', to='pets.pet'),
        ),
    ]
