# Generated by Django 4.1.4 on 2022-12-07 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_alter_trait_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='07/12%/2022, 23:30:14'),
            preserve_default=False,
        ),
    ]
