# Generated by Django 4.1.4 on 2022-12-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0003_trait_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='created_at',
            field=models.DateField(verbose_name='08/12%/2022, 00:02:13'),
        ),
    ]
