# Generated by Django 4.1.4 on 2022-12-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0005_alter_trait_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
